site_name: AWS Learning Process
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.png
  favicon: images/favicon.png

use_directory_urls: false
docs_dir: docs

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Cloud Overview: cloud-overview.md
  - Machine Learning: machine-learning.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - tags

extra:
  generator: false